# Generated by Django 2.1.7 on 2019-02-18 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('slug', models.CharField(default='', max_length=100)),
                ('description', models.TextField(default='')),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Loại Sản phẩm',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255, verbose_name='Tiêu đề')),
                ('description', models.TextField(default='', verbose_name='Mô tả')),
                ('product_img', models.ImageField(upload_to='products/', verbose_name='Ảnh sản phẩm')),
                ('price', models.IntegerField(default=0, verbose_name='giá tiền')),
                ('active', models.BooleanField(default=True, verbose_name='trạng thái')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Category', verbose_name='Loại sản phẩm')),
            ],
            options={
                'verbose_name_plural': 'Sản phẩm',
            },
        ),
        migrations.CreateModel(
            name='Variation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255, verbose_name='Tiêu đề')),
                ('price', models.IntegerField(default=0, verbose_name='Giá tiền')),
                ('sale_price', models.IntegerField(default=0, verbose_name='Giá sale')),
                ('inventory', models.IntegerField(default=0, verbose_name='Tồn kho')),
                ('active', models.BooleanField(default=True, verbose_name='Trạng thái')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product', verbose_name='sản phẩm')),
            ],
            options={
                'verbose_name_plural': 'Sản phẩm change',
            },
        ),
    ]
