# Generated by Django 2.1.7 on 2019-02-18 10:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='số lượng')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Variation', verbose_name='sản phẩm')),
            ],
            options={
                'verbose_name_plural': 'Chi tiết hóa đơn',
            },
        ),
        migrations.CreateModel(
            name='Bills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo hóa đơn')),
                ('bill_description', models.TextField(verbose_name='Mô tả hóa đơn')),
                ('bill_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bills.BillDetail', verbose_name='chi tiết hóa đơn')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='người tạo hóa đơn')),
            ],
            options={
                'verbose_name_plural': 'Hóa đơn',
            },
        ),
    ]
