# Generated by Django 2.1.4 on 2019-02-19 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bills',
            name='bill_description',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Mô tả hóa đơn'),
        ),
    ]
