# Generated by Django 2.1.4 on 2019-02-19 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0002_auto_20190219_0708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bills',
            name='bill_detail',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='bills.BillDetail', verbose_name='chi tiết hóa đơn'),
        ),
    ]
