# Generated by Django 2.1.4 on 2019-02-19 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0003_auto_20190219_0709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bills',
            name='bill_detail',
        ),
        migrations.AddField(
            model_name='billdetail',
            name='bill',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='bills.Bills', verbose_name='Hóa đơn'),
        ),
    ]
