# Generated by Django 2.1.7 on 2019-02-18 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=200, verbose_name='tên nhà cung cấp')),
                ('supplier_address', models.CharField(max_length=200, null=True, verbose_name='địa chỉ nhà cung cấp')),
                ('supplier_phone', models.CharField(max_length=200, null=True, verbose_name='số điện thoại')),
                ('supplier_description', models.TextField(null=True, verbose_name='mô tả nhà cung cấp')),
            ],
            options={
                'verbose_name_plural': 'Nhà cung cấp',
            },
        ),
    ]
