# Generated by Django 2.1.7 on 2019-02-18 10:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_name', models.CharField(max_length=200, verbose_name='Tên báo cáo')),
                ('report_time', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo báo cáo')),
                ('tienhang', models.IntegerField(default=0, verbose_name='Tổng tiền hàng')),
                ('thu', models.IntegerField(default=0, verbose_name='Tổng số tiền đã thu')),
                ('chi', models.IntegerField(default=0, verbose_name='Tổng số tiền đã chi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Người tạo báo cáo')),
            ],
            options={
                'verbose_name_plural': 'Báo cáo',
            },
        ),
    ]
